import { useEffect, useState } from 'react';
import { Plus } from 'lucide-react';
import PageHeader from '../components/PageHeader.jsx';
import DataTable from '../components/DataTable.jsx';
import Modal from '../components/Modal.jsx';
import { FormInput, FormSelect, FormTextarea } from '../components/FormInput.jsx';
import { catalogueApi } from '../api/endpoints';
import { currency } from '../utils/format';
const initial={itemName:'',category:'General',price:0,unit:'Piece',availabilityStatus:'Available',description:''};
export default function Catalogue(){const [rows,setRows]=useState([]),[loading,setLoading]=useState(false),[open,setOpen]=useState(false),[form,setForm]=useState(initial); const load=async()=>{setLoading(true);try{const r=await catalogueApi.list();setRows(r.data.data||r.data.items||r.data||[])}catch{setRows([])}finally{setLoading(false)}}; useEffect(()=>{load()},[]); const save=async()=>{await catalogueApi.create(form);setOpen(false);setForm(initial);load()}; const cols=[{key:'itemName',label:'Item'},{key:'category',label:'Category'},{key:'price',label:'Price',render:r=>currency(r.price)},{key:'unit',label:'Unit'},{key:'availabilityStatus',label:'Availability'}]; return <><PageHeader title="Catalogue / Gallery" subtitle="Maintain shop products, dealer catalogue and dalaal market gallery." actions={<button className="btn-primary" onClick={()=>setOpen(true)}><Plus size={16}/> Add Item</button>}/><DataTable columns={cols} rows={rows} loading={loading}/><Modal open={open} title="Add Catalogue Item" onClose={()=>setOpen(false)} footer={<div className="flex justify-end gap-2"><button className="btn-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn-primary" onClick={save}>Save Item</button></div>}><div className="grid gap-4 md:grid-cols-2"><FormInput label="Item Name" value={form.itemName} onChange={e=>setForm({...form,itemName:e.target.value})}/><FormInput label="Category" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><FormInput label="Price" type="number" value={form.price} onChange={e=>setForm({...form,price:Number(e.target.value)})}/><FormInput label="Unit" value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/><FormSelect label="Availability" value={form.availabilityStatus} onChange={e=>setForm({...form,availabilityStatus:e.target.value})}>{['Available','Unavailable','Limited'].map(x=><option key={x}>{x}</option>)}</FormSelect><div className="md:col-span-2"><FormTextarea label="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div></div></Modal></>}
