import { useEffect, useState } from 'react';
import { HandCoins } from 'lucide-react';
import PageHeader from '../components/PageHeader.jsx';
import StatCard from '../components/StatCard.jsx';
import DataTable from '../components/DataTable.jsx';
import Modal from '../components/Modal.jsx';
import { FormInput, FormTextarea } from '../components/FormInput.jsx';
import { dalaliApi } from '../api/endpoints';
import { currency, statusClass } from '../utils/format';

export default function Dalali(){const [summary,setSummary]=useState({}),[rows,setRows]=useState([]),[selected,setSelected]=useState(null),[amount,setAmount]=useState(0),[notes,setNotes]=useState(''),[loading,setLoading]=useState(false); const load=async()=>{setLoading(true);try{const [s,p]=await Promise.all([dalaliApi.summary(),dalaliApi.pending()]);setSummary(s.data.data||s.data||{});setRows(p.data.data||p.data.items||p.data||[])}catch{setRows([])}finally{setLoading(false)}}; useEffect(()=>{load()},[]); const collect=async()=>{await dalaliApi.collect({ledgerEntryId:selected._id, amount:Number(amount), notes});setSelected(null);setAmount(0);load()}; const cols=[{key:'entryNumber',label:'Entry'},{key:'party',label:'Party',render:r=>r.primaryPartyId?.name||r.party?.name||'-'},{key:'dalaliAmount',label:'Dalali',render:r=>currency(r.dalaliAmount)},{key:'dalaliCollectedAmount',label:'Collected',render:r=>currency(r.dalaliCollectedAmount)},{key:'dalaliPendingAmount',label:'Pending',render:r=>currency(r.dalaliPendingAmount)},{key:'dalaliStatus',label:'Status',render:r=><span className={`badge ${statusClass(r.dalaliStatus)}`}>{r.dalaliStatus||'Due'}</span>},{key:'action',label:'Action',render:r=><button className="btn-secondary py-1" onClick={()=>{setSelected(r);setAmount(r.dalaliPendingAmount||0)}}>Collect</button>}]; return <><PageHeader title="Dalali Management" subtitle="Track generated, pending, collected, overdue and waived commission."/><div className="mb-6 grid gap-4 md:grid-cols-3"><StatCard title="Total Dalali" value={currency(summary.totalDalali)} icon={HandCoins}/><StatCard title="Collected" value={currency(summary.collectedDalali)} icon={HandCoins} tone="emerald"/><StatCard title="Pending" value={currency(summary.pendingDalali)} icon={HandCoins} tone="rose"/></div><DataTable columns={cols} rows={rows} loading={loading}/><Modal open={!!selected} title="Collect Dalali" onClose={()=>setSelected(null)} footer={<div className="flex justify-end gap-2"><button className="btn-secondary" onClick={()=>setSelected(null)}>Cancel</button><button className="btn-primary" onClick={collect}>Save Collection</button></div>}><div className="space-y-4"><p className="text-sm text-slate-600">Entry: <b>{selected?.entryNumber}</b></p><FormInput label="Collected Amount" type="number" value={amount} onChange={e=>setAmount(e.target.value)}/><FormTextarea label="Collection Notes" value={notes} onChange={e=>setNotes(e.target.value)}/></div></Modal></>}
