import { useEffect, useState } from 'react';
import { Upload } from 'lucide-react';
import PageHeader from '../components/PageHeader.jsx';
import DataTable from '../components/DataTable.jsx';
import Modal from '../components/Modal.jsx';
import { FormInput, FormSelect, FormTextarea } from '../components/FormInput.jsx';
import { documentsApi } from '../api/endpoints';
import { date } from '../utils/format';

export default function Documents(){const [rows,setRows]=useState([]),[loading,setLoading]=useState(false),[open,setOpen]=useState(false),[file,setFile]=useState(null),[form,setForm]=useState({title:'',documentType:'Receipt',notes:''}); const load=async()=>{setLoading(true);try{const r=await documentsApi.list();setRows(r.data.data||r.data.items||r.data||[])}catch{setRows([])}finally{setLoading(false)}}; useEffect(()=>{load()},[]); const save=async()=>{const fd=new FormData(); if(file) fd.append('file',file); Object.entries(form).forEach(([k,v])=>fd.append(k,v)); await documentsApi.upload(fd); setOpen(false); setFile(null); load()}; const cols=[{key:'title',label:'Title'},{key:'documentType',label:'Type'},{key:'fileType',label:'File Type'},{key:'createdAt',label:'Uploaded',render:r=>date(r.createdAt)},{key:'fileUrl',label:'File',render:r=>r.fileUrl?<a href={r.fileUrl} target="_blank" className="font-semibold text-orange-700">Open</a>:'-'}]; return <><PageHeader title="Documents" subtitle="Bills, receipts, challans, LR copy, agreements and party documents." actions={<button className="btn-primary" onClick={()=>setOpen(true)}><Upload size={16}/> Upload</button>}/><DataTable columns={cols} rows={rows} loading={loading}/><Modal open={open} title="Upload Document" onClose={()=>setOpen(false)} footer={<div className="flex justify-end gap-2"><button className="btn-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn-primary" onClick={save}>Upload</button></div>}><div className="grid gap-4 md:grid-cols-2"><FormInput label="Title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><FormSelect label="Type" value={form.documentType} onChange={e=>setForm({...form,documentType:e.target.value})}>{['Bill','Receipt','Invoice','Challan','LR Copy','Agreement','GST Certificate','PAN','Other'].map(x=><option key={x}>{x}</option>)}</FormSelect><label className="md:col-span-2"><span className="label">File</span><input className="input" type="file" onChange={e=>setFile(e.target.files?.[0])}/></label><div className="md:col-span-2"><FormTextarea label="Notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div></div></Modal></>}
