import { useEffect, useState } from 'react';
import { Plus } from 'lucide-react';
import PageHeader from '../components/PageHeader.jsx';
import DataTable from '../components/DataTable.jsx';
import Modal from '../components/Modal.jsx';
import { FormInput, FormSelect, FormTextarea } from '../components/FormInput.jsx';
import { remindersApi } from '../api/endpoints';
import { date, statusClass } from '../utils/format';
const initial={title:'',reminderType:'Payment Due',dueDate:'',reminderDate:'',priority:'Medium',status:'Pending',notes:''};
export default function Reminders(){const [rows,setRows]=useState([]),[loading,setLoading]=useState(false),[open,setOpen]=useState(false),[form,setForm]=useState(initial); const load=async()=>{setLoading(true);try{const r=await remindersApi.list();setRows(r.data.data||r.data.items||r.data||[])}catch{setRows([])}finally{setLoading(false)}}; useEffect(()=>{load()},[]); const save=async()=>{await remindersApi.create(form);setOpen(false);setForm(initial);load()}; const cols=[{key:'title',label:'Title'},{key:'reminderType',label:'Type'},{key:'dueDate',label:'Due',render:r=>date(r.dueDate)},{key:'priority',label:'Priority'},{key:'status',label:'Status',render:r=><span className={`badge ${statusClass(r.status)}`}>{r.status}</span>}]; return <><PageHeader title="Reminders" subtitle="Payment due, dalali due, follow-up, settlement and document reminders." actions={<button className="btn-primary" onClick={()=>setOpen(true)}><Plus size={16}/> Add Reminder</button>}/><DataTable columns={cols} rows={rows} loading={loading}/><Modal open={open} title="Add Reminder" onClose={()=>setOpen(false)} footer={<div className="flex justify-end gap-2"><button className="btn-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn-primary" onClick={save}>Save Reminder</button></div>}><div className="grid gap-4 md:grid-cols-2"><FormInput label="Title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><FormSelect label="Type" value={form.reminderType} onChange={e=>setForm({...form,reminderType:e.target.value})}>{['Payment Due','Payment Overdue','Dalali Due','Dalali Overdue','Interest Due','Bhaada Due','Settlement Pending','Follow-up Due','Document Missing'].map(x=><option key={x}>{x}</option>)}</FormSelect><FormInput label="Due Date" type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/><FormInput label="Reminder Date" type="date" value={form.reminderDate} onChange={e=>setForm({...form,reminderDate:e.target.value})}/><FormSelect label="Priority" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{['Low','Medium','High'].map(x=><option key={x}>{x}</option>)}</FormSelect><FormSelect label="Status" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['Pending','Completed','Snoozed','Cancelled'].map(x=><option key={x}>{x}</option>)}</FormSelect><div className="md:col-span-2"><FormTextarea label="Notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div></div></Modal></>}
