import { useState } from 'react';
import { Download, FileSpreadsheet } from 'lucide-react';
import PageHeader from '../components/PageHeader.jsx';
import DataTable from '../components/DataTable.jsx';
import { reportsApi } from '../api/endpoints';
import { currency, date, statusClass } from '../utils/format';

function downloadBlob(blob, filename){ const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=filename; a.click(); URL.revokeObjectURL(url); }
export default function Reports(){const [rows,setRows]=useState([]),[loading,setLoading]=useState(false),[params,setParams]=useState({from:'',to:''}); const load=async()=>{setLoading(true);try{const r=await reportsApi.ledger(params);setRows(r.data.data||r.data.items||r.data||[])}catch{setRows([])}finally{setLoading(false)}}; const exportExcel=async()=>{const r=await reportsApi.exportLedgerExcel(params); downloadBlob(r.data, `ledger-report-${Date.now()}.xlsx`)}; const cols=[{key:'entryNumber',label:'Entry'},{key:'entryDate',label:'Date',render:r=>date(r.entryDate||r.createdAt)},{key:'entryType',label:'Type'},{key:'party',label:'Party',render:r=>r.primaryPartyId?.name||r.partyName||'-'},{key:'totalAmount',label:'Amount',render:r=>currency(r.totalAmount)},{key:'paymentStatus',label:'Status',render:r=><span className={`badge ${statusClass(r.paymentStatus)}`}>{r.paymentStatus||'-'}</span>}]; return <><PageHeader title="Reports" subtitle="Ledger, settlement, outstanding and dalali reporting with Excel export." actions={<><input type="date" className="input w-40" value={params.from} onChange={e=>setParams({...params,from:e.target.value})}/><input type="date" className="input w-40" value={params.to} onChange={e=>setParams({...params,to:e.target.value})}/><button className="btn-secondary" onClick={load}><FileSpreadsheet size={16}/> Generate</button><button className="btn-primary" onClick={exportExcel}><Download size={16}/> Export Excel</button></>}/><div className="mb-6 grid gap-4 md:grid-cols-4"><div className="card"><h3 className="font-bold">Daily Ledger</h3><p className="mt-2 text-sm text-slate-500">Transactions and collections.</p></div><div className="card"><h3 className="font-bold">Dalali Report</h3><p className="mt-2 text-sm text-slate-500">Pending, collected, waived.</p></div><div className="card"><h3 className="font-bold">Settlement Report</h3><p className="mt-2 text-sm text-slate-500">Completed and reversed.</p></div><div className="card"><h3 className="font-bold">Ageing Report</h3><p className="mt-2 text-sm text-slate-500">30/60/90/180+ days.</p></div></div><DataTable columns={cols} rows={rows} loading={loading}/></>}
